# Generated by Django 2.2.12 on 2020-11-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
