# Generated by Django 2.2.12 on 2020-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201116_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
