# Generated by Django 2.2.12 on 2020-12-15 10:39

import GCR.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_code', models.CharField(default=GCR.models.CREATE_CODE, max_length=32)),
                ('classroom_subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_role', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='Student', max_length=20)),
                ('user_roll', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_topic', models.CharField(default='', max_length=50)),
                ('post_content', models.TextField()),
                ('post_timestamp', models.DateTimeField(auto_now_add=True)),
                ('post_classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_classroom', to='GCR.Classroom')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_clicked', models.BooleanField(default=False)),
                ('notification_type', models.CharField(default=None, max_length=20)),
                ('notification_classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_classroom', to='GCR.Classroom')),
                ('notification_student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_topic', models.CharField(default=None, max_length=50)),
                ('material_content', models.TextField(default=None, max_length=1000)),
                ('material_classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='material_classroom', to='GCR.Classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_topic', models.CharField(default='', max_length=20)),
                ('assignment_content', models.TextField()),
                ('assigned_classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classroom', to='GCR.Classroom')),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
