# Generated by Django 2.2.12 on 2020-12-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GCR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
